# language: csharp
# mono: none
# dotnet: 3.1.100
# solution: CostIncome.sln
matrix:
  include:
    - name: Build on linux bionic beaver
      os: linux
      dist: bionic
      language: csharp
      mono: none
      dotnet: 3.1.100
      solution: CostIncome.sln
    - name: Test on linux bionic beaver
      os: linux
      dist: bionic
      language: csharp
      mono: none
      dotnet: 3.1.100
      solution: CostIncome.sln

jobs:
  include:
    - stage: build
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: test
      script: 
        - dotnet test