language: csharp
mono: none
dotnet: 3.1.100
solution: CostIncome.sln
jobs:
  include:
    - stage: build
      os:
        - linux
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: test
      os:
        - linux
      script: 
        - dotnet test