jobs:
  include:
    - stage: Build back-end
      language: csharp
      mono: none
      dotnet: 3.1.100
      solution: CostIncome.sln
      jobs:
        include:
          - stage: Build
            os: linux
            script:
              - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
          - Stage: Test
            os: linux
            script:
              - dotnet test
    - stage: Build front-end
      language: node.js
      node_js: "12.0"
      before_script:
        - cd client
      script:
        - npm install
        - npm run build