jobs:
  include:
    - stage: Backend build
      language: csharp
      mono: none
      dotnet: 3.1.100
      solution: CostIncome.sln
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: Backend test
      language: csharp
      mono: none
      dotnet: 3.1.100
      solution: CostIncome.sln
      script:
        - dotnet test
    - stage: Build front-end
      language: node.js
      node_js: 12.0
      before_script:
        - cd client
      script:
        - npm install
        - npm run build