language: csharp
mono: none
dotnet: 2.2.401
solution: CostIncome.sln
jobs:
  include:
    - stage: build
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: test
      script: 
        - dotnet test