language: csharp
os:
 - linux
 - osx
mono: none
dotnet: 3.1.100
solution: CostIncome.sln
jobs:
  include:
    - stage: build
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: test
      script: 
        - dotnet test