language: csharp
mono: none
dotnet: 3.1.100
solution: CostIncome.sln
jobs:
  include:
    - stage: Build on linux bionic beaver
      os: linux
      dist: bionic
      script:
        - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
    - stage: Test on linux bionic beaver
      os: linux
      dist: bionic
      script: 
        - dotnet test