language: csharp
mono: none
dotnet: 3.1.100
solution: CostIncome.sln
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.3
    - os: windows
        

script:
  - dotnet build ./CostIncomeCalculator/CostIncomeCalculator.csproj
  - dotnet test