using System;
using FluentEmail.Core;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace CostIncomeCalculator.Helpers
{
    /// <summary>
    /// Email template helper.
    /// </summary>
    public class EmailHelper : IEmailHelper
    {
        private readonly IFluentEmail fluentEmail;
        private readonly ILogger logger;
        /// <summary>
        /// Email helper constructor.
        /// </summary>
        /// <param name="fluentEmail">FluentEmail email sender.</param>
        /// <param name="logger">Serilog logger.</param>
        public EmailHelper([FromServices] IFluentEmail fluentEmail, ILogger logger)
        {
            this.logger = logger;
            this.fluentEmail = fluentEmail;

        }
        /// <summary>
        /// Get html template for reset password complete message.
        /// </summary>
        /// <param name="email">User email</param>
        /// <param name="newPassword">New user password</param>
        /// <returns></returns>
        public async void SendResetPasswordEmail(string email, string newPassword)
        {
            try
            {
                string currentDate = $"{DateTime.Now.ToShortDateString()}, {DateTime.Now.ToShortTimeString()}";

                await fluentEmail
                    .To(email)
                    .Subject($"Reset password on CostIncome {currentDate}")
                    .Body($@"<p>Dear {email}!</p>
                        <p>Your new password is <strong>{newPassword}.</strong></p>
                        <hr/>
                        <p><strong>Please, change this autogenerated password as soon as possible!</strong></p>", true)
                    .SendAsync();
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                throw;
            }
        }
    }
}